version: "3.7"

services:
  frontend:
    build: frontend/
    ports:
      - "8082:80"
    environment:
      MY_ENV_VAR: Hello world
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3006
  ubuntu:
    image: ubuntu:20.04
    tty: true
